// Experiments/Experiment_10/student-app/src/App.jsx
import { useState } from 'react';
import AddStudent from './components/AddStudent';
import StudentList from './components/StudentList';
import './App.css';

function App() {

  const [students, setStudents] = useState([
    { id: 1, name: 'Rahul', age: 20, course: 'CSE' },
    { id: 2, name: 'Priya', age: 21, course: 'IT' }
  ]);

  const addStudent = (student) => {
    setStudents([...students, student]);
  };

  return (
    <div className="container">
      <h3>Student Management System</h3>

      <AddStudent onAdd={addStudent} />

      <StudentList students={students} />
    </div>
  );
}

export default App;

// Experiments/Angular/Experiment_08/student-app/src/app/app.ts
import { Component } from '@angular/core';
import { AddStudent } from './add-student/add-student';
import { ViewStudent } from './view-student/view-student';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [AddStudent, ViewStudent],
  templateUrl: './app.html',
  styleUrls: ['./app.css']
})
export class App {

  students = [
    { id: 1, name: 'Rahul', age: 20, course: 'CSE' },
    { id: 2, name: 'Priya', age: 21, course: 'IT' }
  ];

  addStudent(student: any) {
    this.students.push(student);
  }
}
