// Experiments/Angular/Experiment_08/student-app/src/app/app.ts
import { Component } from '@angular/core';
import { AddStudent } from './add-student/add-student';
import { ViewStudent } from './view-student/view-student';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [AddStudent, ViewStudent],
  templateUrl: './app.html',
  styleUrls: ['./app.css']
})
export class App {

  students = [
    { id: 1, name: 'Rahul', age: 20, course: 'CSE' },
    { id: 2, name: 'Priya', age: 21, course: 'IT' }
  ];

  addStudent(student: any) {
    this.students.push(student);
  }
}

// Experiments/Experiment_11/student-dashboard/src/App.jsx
import { useState } from 'react';
import Dashboard from './components/Dashboard';

function App() {

  const [students, setStudents] = useState([
    { id: 1, name: 'Rahul', age: 20, course: 'CSE' },
    { id: 2, name: 'Priya', age: 21, course: 'IT' }
  ]);

  // ADD
  const addStudent = (student) => {
    setStudents([...students, student]);
  };

  // DELETE
  const deleteStudent = (id) => {
    setStudents(students.filter(s => s.id !== id));
  };

  return (
    <Dashboard
      students={students}
      addStudent={addStudent}
      deleteStudent={deleteStudent}
    />
  );
}

export default App;
